version: "v2.17.2"

services:
  # Backend API
  link-saver-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /link-saver-api
    environment:
      - POSTGRES_URI=postgres://sally:a776357748@postgres:5432/link-saver-db
      - REDIS_URI=redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/link-saver-api
      - /link-saver-api/node_modules

  # Postgres
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=sally
      - POSTGRES_PASSWORD=a776357748
      - POSTGRES_DB=link-saver-db
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
